### ISSUE TITLE
A listing file

### ISSUE THREAD

**Issue by ghost** [breakintoprogram/agon-projects#13]
I have a newly minted Z80 (legacy) cross-assembler I'm trying to finalize.
I can assemble the hello world 16 program, using macros for RST.LIS and the like.
I would love to see a listing file of that project from someone that has the Zilog assembler installed.
I don't, for some reasons. What I am really after is to cross check my work against a known standard.

 - Wes

**Comment by breakintoprogram** [comment]
Apologies for the delay in getting back to you on this - attached is the .lst files for the Hello World 16 project as requested.

- [main.lst.txt](https://github.com/breakintoprogram/agon-projects/files/13438938/main.lst.txt)
- [init.lst.txt](https://github.com/breakintoprogram/agon-projects/files/13438939/init.lst.txt)

Hope that helps.

**Comment by ghost** [comment]
TYVM seems like a terse response. But I really mean it.

 - Wes
